(* ::Package:: *)

(* ::Input:: *)
(*(*0. Import data*)*)
(*(* title.ratings.tsv can be found at https://developer.imdb.com/non-commercial-datasets/*) *)
(*data=Import["title.ratings.tsv","TSV"];*)
(*headers=First[data];*)
(*rows=Rest[data];*)


(* ::Input:: *)
(*(*1. Identify column indices*)tconstIndex=First@FirstPosition[headers,"tconst"];*)
(*ratingIndex=First@FirstPosition[headers,"averageRating"];*)
(*numVotesIndex=First@FirstPosition[headers,"numVotes"];*)
(**)
(*(*2. Convert original ratings and votes to numeric arrays*)*)
(*origRatings=ToExpression[rows[[All,ratingIndex]]];*)
(*votesRaw=rows[[All,numVotesIndex]];*)
(*votes=ToExpression/@StringReplace[ToString/@votesRaw,","->""];*)
(*allTconsts=rows[[All,tconstIndex]];*)
(**)
(*(*3. Filter to only titles with more than 500 votes*)*)
(*filteredIdx=Flatten@Position[votes,_?(#>500&)];*)
(*filteredRatings=origRatings[[filteredIdx]];*)
(*filteredRows=rows[[filteredIdx]];*)
(**)
(*(*4. Sort filtered data*)*)
(*sortedIdx=Ordering[filteredRatings];*)
(*sortedRatings=filteredRatings[[sortedIdx]];*)
(*sortedRows=filteredRows[[sortedIdx]];*)
(**)
(*(*5. Compute basic metrics of sorted data*)*)
(*count=Length[sortedRatings];*)
(*mean=N[Mean[sortedRatings],6];*)
(*median=N[Median[sortedRatings],6];*)
(*deviation=N[StandardDeviation[sortedRatings],6];*)
(**)
(*(*6. Transform via probability-integral then inverse-normal to[1,10] centered at 5.5*)*)
(*cdf=EmpiricalDistribution[sortedRatings];*)
(*u=CDF[cdf]/@sortedRatings;*)
(*z=InverseCDF[NormalDistribution[0,1],u];*)
(*halfWidth=4.5;*)
(*sdScale=halfWidth/Quantile[NormalDistribution[0,1],0.998];*)
(*normalizedVals=Clip[5.5+sdScale*z,{1,10}];*)
(*normalizeNumberString[n_]:=Module[{s=ToString@NumberForm[N[Round[n,0.1]],{3,1}]},If[StringEndsQ[s,".0"],StringDrop[s,-2],s]];*)
(*normalizedOneDec=normalizeNumberString/@normalizedVals;*)
(**)
(*(*7. Plot comparison histograms of original and transformed ratings*)*)
(*Show[{Histogram[sortedRatings,{0.5},"Probability",ChartStyle->Directive[Blue]],Histogram[normalizedVals,{0.5},"Probability",ChartStyle->Directive[Green,Opacity[0.5]]]},PlotLabel->Row[{"Original (Blue)\n","Transformed (Green)\n\n","Original \[RightArrow] Count: ",count,", Mean: ",mean,", Median: ",median,", SD: ",deviation,"\n","Transformed Count: ",count,", Mean: ",N[Mean[normalizedVals],6],", Median: ",N[Median[normalizedVals],6],", SD: ",N[StandardDeviation[normalizedVals],6]}]]*)
(**)
(*(*8. Display table of 10 lowest and 10 highest rated filtered movies*)*)
(*lowIdx=Range[1,Min[10,count]];*)
(*highIdx=Range[count-Min[10,count]+1,count];*)
(*tableIdx=Join[lowIdx,highIdx];*)
(*TableForm[Table[{sortedRows[[i,tconstIndex]],NumberForm[sortedRatings[[i]],{Infinity,1},NumberPadding->{"","0"}],NumberForm[normalizedVals[[i]],{Infinity,1},NumberPadding->{"","0"}]},{i,tableIdx}],TableHeadings->{None,{"tconst","OriginalRating","NormalizedRating"}},TableAlignments->Center]*)
(**)
(*(*8a.Table of specific titles before and after normalization*)*)
(*specialTconsts={"tt0111161","tt6208148"};*)
(*specialRatings=Association@Map[Function[tc,tc->{If[KeyExistsQ[origMap,tc],origMap[tc],"-"],If[KeyExistsQ[normalMap,tc],normalMap[tc],origMap[tc]<>"*"]}],specialTconsts];*)
(*TableForm[Prepend[Map[Function[{k},Prepend[specialRatings[k],k]],Keys[specialRatings]],{"tconst","OriginalRating","NormalizedRating"}]]*)


(* ::Input:: *)
(*(*9. Export only updated normalized ratings as JSON*)exportAssoc=Association@MapThread[Rule[#1,<|"r"->ToExpression[#2]|>]&,{sortedRows[[All,tconstIndex]],normalizedOneDec}];*)
(*jsonText=StringJoin["{\n",StringRiffle[("\""<>#<>"\": {\"r\": "<>ToString[exportAssoc[#]["r"]]<>"}")&/@Keys[exportAssoc],",\n"],"\n}\n"];*)
(*Export["title.ratings.normalized.withUnchanged.json",jsonText,"Text"];*)
